# Docker Compose файл для настройки и запуска контейнеров для проекта MongoTracker.Sample.
# Включает в себя контейнеры для MongoDB, Mongo Express и самого приложения MongoTracker.Sample.

services:

  # Сервис для MongoDB
  nest.mongo:
    image: mongo:latest # Используем последний официальный образ MongoDB
    ports:
      - "27017:27017" # Пробрасываем порт 27017 для доступа к Mongo с хоста
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Имя пользователя для администратора MongoDB
      MONGO_INITDB_ROOT_PASSWORD: toor # Пароль для администратора MongoDB

  # Сервис для Mongo Express (веб-интерфейс для управления MongoDB)
  nest.mongo-express:
    image: mongo-express:latest # Используем последний официальный образ Mongo Express
    ports:
      - "8081:8081" # Пробрасываем порт 8081 для доступа к Mongo Express с хоста
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@nest.mongo:27017/admin # URL для подключения к MongoDB
      ME_CONFIG_BASICAUTH: "false" # Отключаем аутентификацию в веб-интерфейсе
    depends_on:
      - nest.mongo # Зависимость от сервиса MongoDB (ждем запуска MongoDB перед запуском Mongo Express)